[project]
name = "preflight-check"
version = "0.1.0"
description = "A tool to ensure your Azure environment is properly configured for deploying the Lacework Agentless Scanner."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.20.0",
    "azure-mgmt-compute>=34.0.0",
    "azure-mgmt-subscription>=3.1.1",
    "rich>=13.9.4",
    "typer>=0.15.1",
]
